name: Rust

on:
    workflow_dispatch:
    # push:
    #     branches: [main]
    # pull_request:
    #     branches: [main]

env:
    NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - run: cargo test --all-features
