name: PR Checks

on:
    pull_request:
        types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
    check-title:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR title
              uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  validateSingleCommit: false
                  types:
                      - feat
                      - fix
                      - docs
                      - style
                      - refactor
                      - perf
                      - test
                      - build
                      - ci
                      - chore
                      - revert
